apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: splunk-operator
  name: splunk-operator-app-download
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
