apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    name: splunk-operator
  name: splunk-operator-controller-manager-service
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  ports:
  - name: metric
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: health
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    control-plane: controller-manager
    name: splunk-operator
