{{- if eq .Values.global.clusterScope "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    name: splunk-operator
  name: splunk-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: splunk-operator-manager-role
subjects:
- kind: ServiceAccount
  name: splunk-operator-controller-manager
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    name: splunk-operator
  name: splunk-operator-manager-rolebinding
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: splunk-operator-manager-role
subjects:
- kind: ServiceAccount
  name: splunk-operator-controller-manager
  namespace: splunk-operator
{{- end }}
