{{- if and .Values.route .Values.route.enabled }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.route.name }}
  namespace: {{ .Release.Namespace }}
spec:
  to:
    kind: Service
    weight: 100
  port:
    targetPort: {{ .Values.route.targetPort }}
{{- if .Values.route.tls }}
  tls:
{{- toYaml .Values.route.tls | nindent 4 }}
{{- end }}
  wildcardPolicy: None
{{- end }}