apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "alertmanager-jira.configname" . }} 
stringData:
  jiralert.tmpl: |
    {{`{{ define "jira.summary" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }} {{ if gt (len .CommonLabels) (len .GroupLabels) }}({{ with .CommonLabels.Remove .GroupLabels.Names }}{{ .Values | join " " }}{{ end }}){{ end }}{{ end }}

    {{ define "jira.description" }}{{ range .Alerts.Firing }}Labels:
    {{ range .Labels.SortedPairs }} - {{ .Name }} = {{ .Value }}
    {{ end }}
    Annotations:
    {{ range .Annotations.SortedPairs }} - {{ .Name }} = {{ .Value }}
    {{ end }}
    Source: {{ .GeneratorURL }}
    {{ end }}{{ end }}`}}
  jiralert.yml: |
    defaults:
      api_url: {{ .Values.jira.api_url }} 
      user: {{ .Values.jira.user }}
      password: {{ .Values.jira.password }}
      issue_type: Bug
    {{`
      priority: Critical
      summary: '{{ template "jira.summary" . }}'
      description: '{{ template "jira.description" . }}'`}}
      reopen_state: "To Do"
      wont_fix_resolution: "Won't Fix"
      reopen_duration: 0h

    receivers:
      - name: 'jiralert'
        project: {{ .Values.jira.project }} 
        add_group_labels: false

    template: jiralert.tmpl
