apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: stakater-mattermost                         # Chose the desired name
  namespace: mattermost-operator
spec:
  probes:
    livenessProbe:
      httpGet:
        path: /api/v4/system/ping
        port: 8065
        scheme: HTTP
      initialDelaySeconds: 20
      timeoutSeconds: 60
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /api/v4/system/ping
        port: 8065
        scheme: HTTP
      initialDelaySeconds: 20
      timeoutSeconds: 60
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 6
  size: 500users                               # Adjust to your requirements
  replicas: 2
  scheduling:
    resources:
      limits:
        cpu: '2'
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 500Mi
  ingress:
    enabled: true
    host: stakater-mattermost-mattermost-operator.apps.devtest.vxdqgl7u.kubeapp.cloud       # Adjust to your domain
    annotations:
      kubernetes.io/ingress.class: nginx
  version: 6.0.1
  licenseSecret: ""                             # If you have created secret in step 1, put its name here
  database:
    external:
      secret: mattermost-postgres-connection      # Name of a Kubernetes secret that contains connection string to external database.
  fileStore:
    external:
      url: http://minio.mattermost-operator.svc:80
      bucket: test
      secret: minio-creds-secret