apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
spec:
  serviceAccountName: minio-tenant
  console:
    consoleSecret:
      name: console-secret
    replicas: 1
  credsSecret:
    name: minio-creds-secret
  pools:
    - servers: 2
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 4Gi
          storageClassName: stakater
      volumesPerServer: 2
  requestAutoCert: false
  serviceMetadata:
    consoleServiceAnnotations:
      v2.min.io: console-svc
    consoleServiceLabels:
      label: console-svc
    minioServiceAnnotations:
      v2.min.io: minio-svc
    minioServiceLabels:
      label: minio-svc

---
apiVersion: v1
kind: Secret
metadata:
  name: "minio-creds-secret"
type: Opaque
data:
  ## Access Key for MinIO Tenant
  accesskey: "bWluaW8="
  ## Secret Key for MinIO Tenant
  secretkey: "bWluaW8xMjM="

---
apiVersion: v1
kind: Secret
metadata:
  name: console-secret
data:
  CONSOLE_ACCESS_KEY: YWRtaW4=
  CONSOLE_PBKDF_PASSPHRASE: YWRtaW4=
  CONSOLE_PBKDF_SALT: YWRtaW4=
  CONSOLE_SECRET_KEY: YWRtaW4=

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minio-tenant-role
rules:
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - update
      - list
  - apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - events
      - configmaps
    verbs:
      - get
      - watch
      - create
      - list
      - delete
      - deletecollection
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - watch
      - create
      - update
      - list
      - delete
      - deletecollection
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - deployments
      - deployments/finalizers
    verbs:
      - get
      - create
      - list
      - patch
      - watch
      - update
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - create
      - list
      - patch
      - watch
      - update
      - delete
  - apiGroups:
      - "certificates.k8s.io"
    resources:
      - "certificatesigningrequests"
      - "certificatesigningrequests/approval"
      - "certificatesigningrequests/status"
    verbs:
      - update
      - create
      - get
      - delete
      - list
  - apiGroups:
      - certificates.k8s.io
    resourceNames:
      - kubernetes.io/legacy-unknown
      - kubernetes.io/kube-apiserver-client
      - kubernetes.io/kubelet-serving
      - beta.eks.amazonaws.com/app-serving
    resources:
      - signers
    verbs:
      - approve
      - sign
  - apiGroups:
      - minio.min.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - min.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheuses
    verbs:
      - '*'
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - get
      - update
      - create
  - apiGroups:
      - security.openshift.io 
    resourceNames:
      - anyuid
    resources:
      - securitycontextconstraints 
    verbs: 
      - use

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minio-tenant-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: minio-tenant-role
subjects:
  - kind: ServiceAccount
    name: minio-tenant
    namespace: mattermost-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-tenant
  namespace: mattermost-operator