apiVersion: v1
kind: ConfigMap
metadata:
  name: oauthservice-db-init
  namespace: mattermost-operator
data:
  init.sh: |-
    #!/bin/bash
    echo "Waiting 4 minutes for database schema to be created..."
    sleep 4m
    PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -d $DATABASE_NAME -U $DB_USER
    echo "Database login successful."
    check_if_table_exists_and_insert_data () { 
        echo "Checking if table exists in database..."
        count_exists=`PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -d $DATABASE_NAME -U $DB_USER -At -c "SELECT COUNT(*) FROM information_schema.tables WHERE table_catalog = 'oauthservice-db' AND table_name = 'client';"`
        if [[ $count_exists -gt 0 ]]; then
            echo "Table exists in database; inserting data..."
            PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -d $DATABASE_NAME -U $DB_USER -c "INSERT INTO client (id, secret, extra, redirect_uri) VALUES('signtest.csn.se', '8466c5d6-1596-4d1c-802c-4a2855ce4b45', '', 'https://signtest.csn.se');"
            echo "Data inserted successfully"
        elif [[ $count_exists -eq 0 ]]; then
            echo "Table not found. Waiting 1 minute before trying again..."
            sleep 1m
            echo "Invoking recursion..."
            check_if_table_exists_and_insert_data
        fi
    }
    check_if_table_exists_and_insert_data